version: 2
updates:
  # Dependencies front (client)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Dependencies back (server) - adapt the ecosystem to your situation
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"